
language: python
python:
    - '2.6'
    - '2.7'
    - '3.2'
    - '3.3'

install:
    - pip install . --use-mirrors
    - pip install -r requirements.txt --use-mirrors

script:
    - py.test
    - flake8 --exclude='.tox,build' --max-complexity 7
